// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: perception.proto

package perceptionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Perception_Health_FullMethodName = "/perception.Perception/Health"
	Perception_Ocr_FullMethodName    = "/perception.Perception/Ocr"
)

// PerceptionClient is the client API for Perception service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Perception is the OCR sidecar service: turn a frame into structured text+boxes.
type PerceptionClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error)
	Ocr(ctx context.Context, in *OcrRequest, opts ...grpc.CallOption) (*OcrReply, error)
}

type perceptionClient struct {
	cc grpc.ClientConnInterface
}

func NewPerceptionClient(cc grpc.ClientConnInterface) PerceptionClient {
	return &perceptionClient{cc}
}

func (c *perceptionClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, Perception_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *perceptionClient) Ocr(ctx context.Context, in *OcrRequest, opts ...grpc.CallOption) (*OcrReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OcrReply)
	err := c.cc.Invoke(ctx, Perception_Ocr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PerceptionServer is the server API for Perception service.
// All implementations must embed UnimplementedPerceptionServer
// for forward compatibility.
//
// Perception is the OCR sidecar service: turn a frame into structured text+boxes.
type PerceptionServer interface {
	Health(context.Context, *HealthRequest) (*HealthReply, error)
	Ocr(context.Context, *OcrRequest) (*OcrReply, error)
	mustEmbedUnimplementedPerceptionServer()
}

// UnimplementedPerceptionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPerceptionServer struct{}

func (UnimplementedPerceptionServer) Health(context.Context, *HealthRequest) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPerceptionServer) Ocr(context.Context, *OcrRequest) (*OcrReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ocr not implemented")
}
func (UnimplementedPerceptionServer) mustEmbedUnimplementedPerceptionServer() {}
func (UnimplementedPerceptionServer) testEmbeddedByValue()                    {}

// UnsafePerceptionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PerceptionServer will
// result in compilation errors.
type UnsafePerceptionServer interface {
	mustEmbedUnimplementedPerceptionServer()
}

func RegisterPerceptionServer(s grpc.ServiceRegistrar, srv PerceptionServer) {
	// If the following call panics, it indicates UnimplementedPerceptionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Perception_ServiceDesc, srv)
}

func _Perception_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerceptionServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Perception_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerceptionServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Perception_Ocr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OcrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PerceptionServer).Ocr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Perception_Ocr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PerceptionServer).Ocr(ctx, req.(*OcrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Perception_ServiceDesc is the grpc.ServiceDesc for Perception service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Perception_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "perception.Perception",
	HandlerType: (*PerceptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Perception_Health_Handler,
		},
		{
			MethodName: "Ocr",
			Handler:    _Perception_Ocr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "perception.proto",
}
