// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: perception.proto

package perceptionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_perception_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{0}
}

type HealthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	Ocr           string                 `protobuf:"bytes,2,opt,name=ocr,proto3" json:"ocr,omitempty"`       // "rapidocr" | "stub"
	Err           string                 `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`       // init error, if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReply) Reset() {
	*x = HealthReply{}
	mi := &file_perception_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReply) ProtoMessage() {}

func (x *HealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReply.ProtoReflect.Descriptor instead.
func (*HealthReply) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{1}
}

func (x *HealthReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthReply) GetOcr() string {
	if x != nil {
		return x.Ocr
	}
	return ""
}

func (x *HealthReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type OcrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"` // PNG-encoded frame
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrRequest) Reset() {
	*x = OcrRequest{}
	mi := &file_perception_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrRequest) ProtoMessage() {}

func (x *OcrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrRequest.ProtoReflect.Descriptor instead.
func (*OcrRequest) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{2}
}

func (x *OcrRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type Box struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W             int32                  `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Conf          float64                `protobuf:"fixed64,6,opt,name=conf,proto3" json:"conf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Box) Reset() {
	*x = Box{}
	mi := &file_perception_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{3}
}

func (x *Box) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Box) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Box) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Box) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *Box) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Box) GetConf() float64 {
	if x != nil {
		return x.Conf
	}
	return 0
}

type OcrReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Boxes         []*Box                 `protobuf:"bytes,2,rep,name=boxes,proto3" json:"boxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OcrReply) Reset() {
	*x = OcrReply{}
	mi := &file_perception_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OcrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OcrReply) ProtoMessage() {}

func (x *OcrReply) ProtoReflect() protoreflect.Message {
	mi := &file_perception_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OcrReply.ProtoReflect.Descriptor instead.
func (*OcrReply) Descriptor() ([]byte, []int) {
	return file_perception_proto_rawDescGZIP(), []int{4}
}

func (x *OcrReply) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OcrReply) GetBoxes() []*Box {
	if x != nil {
		return x.Boxes
	}
	return nil
}

var File_perception_proto protoreflect.FileDescriptor

const file_perception_proto_rawDesc = "" +
	"\n" +
	"\x10perception.proto\x12\n" +
	"perception\"\x0f\n" +
	"\rHealthRequest\"I\n" +
	"\vHealthReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x10\n" +
	"\x03ocr\x18\x02 \x01(\tR\x03ocr\x12\x10\n" +
	"\x03err\x18\x03 \x01(\tR\x03err\"\"\n" +
	"\n" +
	"OcrRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"e\n" +
	"\x03Box\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01w\x18\x03 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x04 \x01(\x05R\x01h\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x12\n" +
	"\x04conf\x18\x06 \x01(\x01R\x04conf\"E\n" +
	"\bOcrReply\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12%\n" +
	"\x05boxes\x18\x02 \x03(\v2\x0f.perception.BoxR\x05boxes2\x7f\n" +
	"\n" +
	"Perception\x12<\n" +
	"\x06Health\x12\x19.perception.HealthRequest\x1a\x17.perception.HealthReply\x123\n" +
	"\x03Ocr\x12\x16.perception.OcrRequest\x1a\x14.perception.OcrReplyB#Z!visionagent/internal/perceptionpbb\x06proto3"

var (
	file_perception_proto_rawDescOnce sync.Once
	file_perception_proto_rawDescData []byte
)

func file_perception_proto_rawDescGZIP() []byte {
	file_perception_proto_rawDescOnce.Do(func() {
		file_perception_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_perception_proto_rawDesc), len(file_perception_proto_rawDesc)))
	})
	return file_perception_proto_rawDescData
}

var file_perception_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_perception_proto_goTypes = []any{
	(*HealthRequest)(nil), // 0: perception.HealthRequest
	(*HealthReply)(nil),   // 1: perception.HealthReply
	(*OcrRequest)(nil),    // 2: perception.OcrRequest
	(*Box)(nil),           // 3: perception.Box
	(*OcrReply)(nil),      // 4: perception.OcrReply
}
var file_perception_proto_depIdxs = []int32{
	3, // 0: perception.OcrReply.boxes:type_name -> perception.Box
	0, // 1: perception.Perception.Health:input_type -> perception.HealthRequest
	2, // 2: perception.Perception.Ocr:input_type -> perception.OcrRequest
	1, // 3: perception.Perception.Health:output_type -> perception.HealthReply
	4, // 4: perception.Perception.Ocr:output_type -> perception.OcrReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_perception_proto_init() }
func file_perception_proto_init() {
	if File_perception_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_perception_proto_rawDesc), len(file_perception_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_perception_proto_goTypes,
		DependencyIndexes: file_perception_proto_depIdxs,
		MessageInfos:      file_perception_proto_msgTypes,
	}.Build()
	File_perception_proto = out.File
	file_perception_proto_goTypes = nil
	file_perception_proto_depIdxs = nil
}
