# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: perception.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'perception.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10perception.proto\x12\nperception\"\x0f\n\rHealthRequest\"7\n\x0bHealthReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0b\n\x03ocr\x18\x02 \x01(\t\x12\x0b\n\x03\x65rr\x18\x03 \x01(\t\"\x1b\n\nOcrRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"M\n\x03\x42ox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x0c\n\x04\x63onf\x18\x06 \x01(\x01\"8\n\x08OcrReply\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1e\n\x05\x62oxes\x18\x02 \x03(\x0b\x32\x0f.perception.Box2\x7f\n\nPerception\x12<\n\x06Health\x12\x19.perception.HealthRequest\x1a\x17.perception.HealthReply\x12\x33\n\x03Ocr\x12\x16.perception.OcrRequest\x1a\x14.perception.OcrReplyB#Z!visionagent/internal/perceptionpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perception_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!visionagent/internal/perceptionpb'
  _globals['_HEALTHREQUEST']._serialized_start=32
  _globals['_HEALTHREQUEST']._serialized_end=47
  _globals['_HEALTHREPLY']._serialized_start=49
  _globals['_HEALTHREPLY']._serialized_end=104
  _globals['_OCRREQUEST']._serialized_start=106
  _globals['_OCRREQUEST']._serialized_end=133
  _globals['_BOX']._serialized_start=135
  _globals['_BOX']._serialized_end=212
  _globals['_OCRREPLY']._serialized_start=214
  _globals['_OCRREPLY']._serialized_end=270
  _globals['_PERCEPTION']._serialized_start=272
  _globals['_PERCEPTION']._serialized_end=399
# @@protoc_insertion_point(module_scope)
